# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybCqkUc29-Ac_PCLB0SYaY29gDDcCKqa
"""

# Programa Python para implementação de Insertion Sort
  
# Função para fazer a classificação por inserção
def insertionSort(arr):
  
   # Atravessar de 1 para len (arr)
    for i in range(1, len(arr)):
  
        key = arr[i]
  
        # Mova os elementos de arr [0..i-1], que são
        # maior que chave, para uma posição à frente
        # de sua posição atual
        j = i-1
        while j >=0 and key < arr[j] :
                arr[j+1] = arr[j]
                j -= 1
        arr[j+1] = key
  
  
# Código do driver para testar acima
arr = [12, 11, 13, 5, 6]
insertionSort(arr)
print ("A matriz ordenada é:")
for i in range(len(arr)):
    print ("%d" %arr[i])